// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (source, category, type, severity, title, message, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, source, category, type, severity, title, message, metadata, created_at
`

type CreateEventParams struct {
	Source   string         `json:"source"`
	Category sql.NullString `json:"category"`
	Type     string         `json:"type"`
	Severity string         `json:"severity"`
	Title    string         `json:"title"`
	Message  string         `json:"message"`
	Metadata sql.NullString `json:"metadata"`
}

type CreateEventRow struct {
	ID        int64          `json:"id"`
	Source    string         `json:"source"`
	Category  sql.NullString `json:"category"`
	Type      string         `json:"type"`
	Severity  string         `json:"severity"`
	Title     string         `json:"title"`
	Message   string         `json:"message"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Source,
		arg.Category,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.Metadata,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Category,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT id, source, type, severity, title, message, metadata, created_at, category
FROM events
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type GetEventsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
