// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	ID        int64          `json:"id"`
	Source    string         `json:"source"`
	Type      string         `json:"type"`
	Severity  string         `json:"severity"`
	Title     string         `json:"title"`
	Message   string         `json:"message"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt time.Time      `json:"created_at"`
	Category  sql.NullString `json:"category"`
}
