// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error)
	GetEvents(ctx context.Context, arg GetEventsParams) ([]Event, error)
}

var _ Querier = (*Queries)(nil)
